import Head from "next/head";
import Page from "@/components/Page";
import CommandTerminal from "@/components/CommandTerminal";
import { FunctionTemplateEnum } from "@/components/CommandTerminal/TemplatesFunction";

const HomeTemplate = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommandTerminal
        pageTitle="home"
        mobileText={`// Hi there! I'm Mathias, \n // building the web \n // one line at a time`}
        desktopText={`// Hi there! I'm Mathias, \n // building the web one line at a time`}
        functions={[
          FunctionTemplateEnum.PORTFOLIO,
          FunctionTemplateEnum.CONTACT_ME,
          FunctionTemplateEnum.SOCIAL_NETWORKS,
        ]}
      />
    </Page>
  );
};

export default HomeTemplate;
