import Head from "next/head";
import Header from "@/components/Header";
import StarsEffect from "@/components/StarsEffect";
import CommandTerminal from "@/components/CommandTerminal";
import { FunctionTemplateEnum } from "@/components/CommandTerminal/TemplatesFunction";
import Footer from "@/components/Footer";
import * as s from "./style";

const SocialTemplate = () => {
  return (
    <s.SocialTemplateContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StarsEffect />

      <Header />
      <s.Main>
        <CommandTerminal
          pageTitle="social"
          mobileText={`// Let's stay connected! \n // Find me on your favorite \n // social network`}
          desktopText={`// Let's stay connected! \n // Find me on your favorite social network`}
        />

        <s.UniverseGlowEffect src="/glow.svg" />
      </s.Main>

      <Footer />
    </s.SocialTemplateContainer>
  );
};

export default SocialTemplate;
