import Head from "next/head";
import Page from "@/components/Page";
import CommandTerminal from "@/components/CommandTerminal";

const PortfolioTemplate = () => {
  const pageTitle = "Portfolio | Mathias Falci";
  const pageDescription =
    "Explore Mathias Falci's portfolio of web development projects. From responsive websites to interactive web applications, each project showcases a commitment to creativity, functionality, and user experience.";

  return (
    <Page title={pageTitle} description={pageDescription}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommandTerminal
        pageTitle="portfolio"
        mobileText={`// Here, you'll discover \n // some of my latest works`}
        desktopText={`// Here, you'll discover some of my latest works`}
      />
    </Page>
  );
};

export default PortfolioTemplate;
