import Head from "next/head";
import Header from "@/components/Header";
import StarsEffect from "@/components/StarsEffect";
import CommandTerminal from "@/components/CommandTerminal";
import Footer from "@/components/Footer";
import * as s from "./style";

const PortfolioTemplate = () => {
  return (
    <s.PortfolioTemplateContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StarsEffect />

      <Header />
      <s.Main>
        <CommandTerminal
          pageTitle="portfolio"
          mobileText={`// Here, you'll discover \n // some of my latest works`}
          desktopText={`// Here, you'll discover some of my latest works`}
        />

        <s.UniverseGlowEffect src="/glow.svg" />
      </s.Main>

      <Footer />
    </s.PortfolioTemplateContainer>
  );
};

export default PortfolioTemplate;
