import Head from "next/head";
import Page from "@/components/Page";
import CommandTerminal from "@/components/CommandTerminal";

const PortfolioTemplate = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommandTerminal
        pageTitle="portfolio"
        mobileText={`// Here, you'll discover \n // some of my latest works`}
        desktopText={`// Here, you'll discover some of my latest works`}
      />
    </Page>
  );
};

export default PortfolioTemplate;
