import Head from "next/head";
import Page from "@/components/Page";
import CommandTerminal from "@/components/CommandTerminal";

const ContactTemplate = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommandTerminal
        pageTitle="contact"
        mobileText={`// Drop me a message below, \n // and let's start a conversation`}
      />
    </Page>
  );
};

export default ContactTemplate;
