export const constants = {
  zIndex: {
    low: 1,
    medium: 5,
    high: 10,
  },
  SEO: {
    keywords: [
      "Frontend Developer",
      "Web Developer",
      "HTML5",
      "CSS3",
      "JavaScript",
      "React.js",
      "Next.js",
      "Responsive Web Design",
      "UI/UX Design",
      "Cross-Browser Compatibility",
      "Mobile-First Development",
      "Web Accessibility",
      "SASS/SCSS",
      "Frontend Frameworks",
      "Single Page Applications (SPAs)",
      "Progressive Web Apps (PWAs)",
      "Web Performance",
      "Git/GitHub",
      "GraphQL",
      "JSON",
      "Component-Based Architecture",
      "Web Standards",
      "SEO-friendly URLs",
      "Responsive Images",
      "Performance Metrics (Lighthouse, etc.)",
      "Code Splitting",
      "Continuous Integration/Continuous Deployment (CI/CD)",
      "Agile Development",
      "Debugging",
    ],
  },
};
